apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "reporter.fullname" . }}
  labels:
    {{- include "reporter.labels" . | nindent 4 }}

subjects:
- kind: ServiceAccount
  name: {{ include "reporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "reporter.fullname" . }}
  apiGroup: rbac.authorization.k8s.io